Python Web Basics/02. Petstagram Project/common/urls.py
from django.urls import path

from common.views import landing_page

urlpatterns = [
    path('', landing_page, name='index'),
]

Python Web Basics/02. Petstagram Project/pets/urls.py
from django.urls import path

from pets.views import list_pets, details_or_comment_pet, like_pet, edit_pet, delete_pet, create_pet

urlpatterns = [
    path('', list_pets, name='list pets'),
    path('detail/<int:pk>/', details_or_comment_pet, name='pet details or comment'),
    path('like/<int:pk>/', like_pet, name='like pet'),
    path('edit/<int:pk>/', edit_pet, name='edit pet'),
    path('delete/<int:pk>/', delete_pet, name='delete pet'),
    path('create/', create_pet, name='create pet'),
]

Python Web Basics/02. Petstagram Project/petstagram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('pets/', include('pets.urls')),
]

Python Web Basics/02. Petstagram Project/common/models.py
from django.db import models

# Create your models here.

Python Web Basics/02. Petstagram Project/pets/models.py
from django.db import models


class Pet(models.Model):
    DOG = 'dog'
    CAT = 'cat'
    PARROT = 'parrot'
    UNKNOWN = 'unknown'

    PET_TYPES = (
        (CAT, 'Cat'),
        (DOG, 'Dog'),
        (PARROT, 'Parrot'),
        (UNKNOWN, 'Unknown')
    )

    type = models.CharField(max_length=7, choices=PET_TYPES, default=UNKNOWN)
    name = models.CharField(max_length=6, blank=False)
    age = models.IntegerField(blank=False)
    description = models.TextField(blank=False)
    image_url = models.URLField(blank=False)

    def __str__(self):
        return f'ID:{self.id}; Name:{self.name}; Age:{self.age}'


class Like(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    test = models.CharField(max_length=2)


class Comment(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    text = models.TextField(blank=False)

Python Web Basics/02. Petstagram Project/pets/forms/comment_form.py
from django import forms


class CommentForm(forms.Form):
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control rounded-2',
            }
        )
    )

Python Web Basics/02. Petstagram Project/pets/forms/pet_form.py
from django import forms

from pets.models import Pet


class PetForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for (_, field) in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Pet
        fields = '__all__'
        widgets = {
            'image_url': forms.TextInput(
                attrs={
                    'id': 'img-input',
                }
            )
        }

Python Web Basics/02. Petstagram Project/common/views.py
from django.shortcuts import render


def landing_page(request):
    return render(request, 'landing_page.html')

Python Web Basics/02. Petstagram Project/pets/views.py
from django.shortcuts import render, redirect

from pets.forms.comment_form import CommentForm
from pets.forms.pet_form import PetForm
from pets.models import Pet, Like, Comment


def list_pets(request):
    context = {
        'pets': Pet.objects.all(),

    }
    return render(request, 'pet_list.html', context)


def details_or_comment_pet(request, pk):
    pet = Pet.objects.get(pk=pk)
    if request.method == 'GET':
        context = {
            'pet': pet,
            'form': CommentForm(),
        }
        return render(request, 'pet_detail.html', context)
    else:
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(text=form.cleaned_data['text'])
            comment.pet = pet
            comment.save()
            return redirect('pet details or comment', pk)

        context = {
            'pet': pet,
            'form': form,
        }
        return render(request, 'pet_detail.html', context)


def persist_pet(request, pet, template_name):
    if request.method == 'GET':
        form = PetForm(instance=pet)
        context = {
            'form': form,
            'pet': pet,
        }
        return render(request, f'{template_name}.html', context)
    else:
        form = PetForm(request.POST, instance=pet)
        if form.is_valid():
            form.save()
            return redirect('pet details or comment', pet.pk)
        context = {
            'form': form,
            'pet': pet,
        }
        return render(request, f'{template_name}.html', context)


def edit_pet(request, pk):
    pet = Pet.objects.get(pk=pk)
    return persist_pet(request, pet, 'pet_edit')


def create_pet(request):
    pet = Pet()
    return persist_pet(request, pet, 'pet_create')


def delete_pet(request, pk):
    pet = Pet.objects.get(pk=pk)
    if request.method == "GET":
        context = {
            'pet': pet,
        }
        return render(request, 'pet_delete.html', context)
    else:
        pet.delete()
        return redirect('list pets')


def like_pet(request, pk):
    pet = Pet.objects.get(pk=pk)
    like = Like(test=str(pk))
    like.pet = pet
    like.save()
    return redirect('pet details or comment', pk)


def comment_pet(request, pk):
    pass

Python Web Basics/02. Petstagram Project/templates/handmade/index.html
{% extends 'shared/shared/site.html' %}
{% load static %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block site_title %}
    Welcome to Petstagram
{% endblock %}

{% block site_content %}
    <section class="banner">
        <header>
            <h1>Welcome to Petstagram</h1>
            <h2>Share your pet's photos.</h2>
        </header>
        <div class="row">
            <div class="col">
                Already have an account?
                {#<button class="button">Sign in</button>#}
                <a href="#" class="button">Sign in</a>
            </div>
            <div class="col">
                Do not have an account?
                <a href="#" class="button">Sign up</a>
            </div>
        </div>
    </section>
{% endblock %}

Python Web Basics/02. Petstagram Project/templates/handmade/landing_page.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <title>Petstagram</title>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
   </head>
   <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
               <a class="nav-link" href="#">Home</a>
               <li class="nav-item">
                  <a class="nav-link" href="#">Login</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link" href="#">Sign Up</a>
               </li>
            </ul>
         </div>
      </nav>
      <div class="container">
         <div class="jumbotron parent">
            <img style="width: 100%" src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png" alt="">
            <div class="absolute">
               <h1 class="display-4">Welcome to Petstagram</h1>
               <p class="lead">Share your pets photos.</p>
               <hr class="my-4">
               <div class="inner cover">
                  <h1 class="cover-heading"></h1>
                  <div class="row">
                     <div class="col-lg-6">
                        <p class="lead">Already have an account? <br><a href="#" class="btn btn-lg btn-secondary">sign in</a></p>
                     </div>
                     <div class="col-lg-6">
                        <p class="lead"> Do not have an account? <br>
                           <a href="#" class="btn btn-lg btn-secondary">sign up</a>
                        </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </body>
   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
   </body>
</html>

Python Web Basics/02. Petstagram Project/templates/handmade/partials/nav.html
<header>
    <nav class="site-nav">
        <ul class="list-horizontal">
            <li class="list-item">
                <a href="{% url 'index' %}">
                    Home
                </a>
            </li>
            <li class="list-item">
                <a href="{% url 'list pets' %}">
                    Pets
                </a>
            </li>
            <li class="list-item">
                <a href="#">
                    Sign in
                </a>
            </li>
            <li class="list-item">
                <a href="#">
                    Sign up
                </a>
            </li>
        </ul>
    </nav>
</header>

Python Web Basics/02. Petstagram Project/templates/handmade/pets/pet_details.html
{% extends 'shared/../shared/site.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/details-pet.css' %}">
{% endblock %}

{% block site_content %}
    <div class="pet-image">
        <img src="{{ pet.image_url }}" alt="image of {{ pet.name }}"/>
    </div>
    <div class="pet-info">
        <ul class="list-pet-details list-horizontal">
            <li class="list-item">
                <span class="underline"> Type:</span> {{ pet.type }}
            </li>
            <li class="list-item">
                <span class="underline"> Name:</span> {{ pet.name }}
            </li>
            <li class="list-item">
                <span class="underline"> Age:</span> {{ pet.age }}
            </li>
        </ul>
        <p>
            Description: {{ pet.description }}
        </p>
        <div class="pet-buttons">
            {#            <a class="button button-blue" href="{% url 'like pet' pet.id %}">Like</a>#}
            <a href="{% url 'like pet' pet.id %}">
                <i class="far fa-heart"></i>
            </a>
        </div>
        Likes: {{ pet.like_set.count }}
    </div>
{% endblock %}

Python Web Basics/02. Petstagram Project/templates/handmade/pets/pets_list.html
{% extends 'shared/../shared/site.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/list-pets.css' %}">
{% endblock %}

{% block site_content %}
    <h1>All pets</h1>
    <ul class="list-horizontal list-pets">
        {% for pet in pets %}
            <li class="list-item">
                <img src="{{ pet.image_url }}" alt="image of {{ pet.name }}">
                <div class="pet-details">
                    <p class="pet-info">{{ pet.type }} {{ pet.name }}, Age: {{ pet.age }}</p>
                    <p class="pet-description">{{ pet.description }}</p>
                    <div class="pet-buttons">
                        <a class="button button-blue" href="{% url 'pet details' pet.id %}">
                            {{ pet.name }}
                        </a>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

Python Web Basics/02. Petstagram Project/templates/handmade/shared/site.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block site_title %}Petstagram{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/clear.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block styles %}
    {% endblock %}
</head>
<body>
{% include 'partials/../partials/nav.html' %}
<div id="root">
    {% block site_content %}
        Petstagram
    {% endblock %}
</div>
</body>
</html>

Python Web Basics/02. Petstagram Project/templates/landing_page.html
{% extends 'shared/site.html' %}
{% block site_content %}

    <div class="jumbotron parent">
        <img style="width: 100%"
             src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png" alt="">
        <div class="absolute">
            <h1 class="display-4">Welcome to Petstagram</h1>
            <p class="lead">Share your pets photos.</p>
            <hr class="my-4">
            <div class="inner cover">
                <h1 class="cover-heading"></h1>
                <div class="row">
                    <div class="col-lg-6">
                        <p class="lead">Already have an account? <br><a href="#"
                                                                        class="btn btn-lg btn-secondary">Login</a></p>
                    </div>
                    <div class="col-lg-6">
                        <p class="lead"> Do not have an account? <br>
                            <a href="#" class="btn btn-lg btn-secondary">Sign Up</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Python Web Basics/02. Petstagram Project/templates/pet_create.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <h1 class="text-center">Add new pet photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" class="furniture-form">
                {{ form }}
                {% csrf_token %}
                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

Python Web Basics/02. Petstagram Project/templates/pet_delete.html
{% extends 'shared/site.html' %}
{% block site_content %}

    <div class="row">
        <div class="col-lg-12 text-center">
            <h1>Are you sure you want to delete {{ pet.name }}?</h1>
            <div class="m-auto d-flex justify-content-center">
                <div class="m-2">
                    <form method="post" action="{% url 'delete pet' pet.pk %}">
                        {% csrf_token %}
                        <button class="btn btn-danger">
                            Confirm
                        </button>
                    </form>
                </div>
                <div class="m-2">
                    <a class="btn btn-primary" href="javascript:history.back()">No, go back</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Python Web Basics/02. Petstagram Project/templates/pet_detail.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <div class="d-flex">
        <div class="d-inline p-2 w-50">
            <img src="{{ pet.image_url }}" class="w-50 rounded mx-auto d-block">
        </div>
        <div class="d-inline p-2 w-50">
            <div class="d-flex justify-content-between">
                <h5><u>Type:</u> {{ pet.type }}</h5>
                <h5><u>Name:</u> {{ pet.name }}</h5>
                <h5><u>Age:</u> {{ pet.age }}</h5>
            </div>
            <p class="mt-2">Description: {{ pet.description }}</p>
            <div>
                <a href="{% url 'edit pet' pet.pk %}" class="btn btn-success">Edit</a>
                <a href="{% url 'delete pet' pet.pk %}" class="btn btn-danger">Delete</a>
            </div>
            <a href="{% url 'like pet' pet.id %}"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
            <p class="mt-2">Likes: {{ pet.like_set.count }}</p>
        </div>
    </div>
    <div class="d-block" style="background-color: #f1e3e3; padding:2%">
        {% if pet.comment_set.count > 0 %}
            {% for comment in pet.comment_set.all %}
                <div class="box">
                    <h5><em>{{ comment.text }}</em></h5>
                    <hr>
                </div>
            {% endfor %}
        {% else %}
            <div class="box">
                <h3>There are no comments for this pet. </h3>
            </div>
        {% endif %}
        <div class="box">
            <form method="post" action="{% url 'pet details or comment' pet.pk %}">
                {{ form }}
                {% csrf_token %}
                <button class="btn btn-primary mt-2" type="submit">Add comment</button>
            </form>
        </div>
    </div>
{% endblock %}

Python Web Basics/02. Petstagram Project/templates/pet_edit.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <h1 class="text-center">Edit pet photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="{% url 'edit pet' pet.pk %}" class="furniture-form">
                {{ form }}
                {% csrf_token %}
                <img id="img_preview" src="{{ pet.image_url }}" class="w-50 rounded mx-auto d-block"/>
                <button class="btn btn-primary mt-2" type="submit">Edit</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
    <script>
        function updateImage() {
            var img = document.getElementById('img_preview');
            var url = this.value;
            img.src = url;
        }

        document.getElementById('img_input')
            .addEventListener('input', updateImage);
    </script>
{% endblock %}

Python Web Basics/02. Petstagram Project/templates/pet_list.html
{% extends 'shared/site.html' %}
{% block site_content %}
    <h1 class='text-center'>All pet photos</h1>
    <div class="row">
        {% for pet in pets %}
            <div class="col-lg-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{ pet.image_url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ pet.type }} {{ pet.name }}, Age: {{ pet.age }}</h5>
                        <p class="card-text">{{ pet.description }}</p>
                        <a href="{% url 'pet details or comment' pet.id %}" class="btn btn-primary">See details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

Python Web Basics/02. Petstagram Project/templates/shared/site.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <a class="nav-link" href="/">Home</a>
            <a class="nav-link" href="{% url 'list pets' %}">All Pet Photos</a>
            <a class="nav-link" href="{% url 'create pet' %}">Add Pet</a>
            <li class="nav-item">
                <a class="nav-link" href="#">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Sign Up</a>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    <div class="jumbotron parent">
        {% block site_content %}
        {% endblock %}
    </div>
</div>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
</body>
</html>